internalAMS/force-app/main/default/objects/Asset_Assignment__c/fields/Asset_Id__c.field-meta.xml
<CustomField>
    <fullName>Asset_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset Id</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset__c.Asset_Status__c</field>
            <operation>equals</operation>
            <value>Not Assigned</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Asset Assignments</relationshipLabel>
    <relationshipName>Asset_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

internalAMS/force-app/main/default/objects/Asset_Assignment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Asset Assignments</relationshipLabel>
    <relationshipName>Asset_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

internalAMS/force-app/main/default/objects/Maintenance__c/fields/Asset_Received_For_Maintenance__c.field-meta.xml
<CustomField>
    <fullName>Asset_Received_For_Maintenance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Asset Received For Maintenance</label>
    <type>Checkbox</type>
</CustomField>

internalAMS/force-app/main/default/objects/Maintenance__c/fields/Assets__c.field-meta.xml
<CustomField>
    <fullName>Assets__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assets</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Maintenances</relationshipLabel>
    <relationshipName>Maintenances</relationshipName>
    <type>Lookup</type>
</CustomField>

internalAMS/force-app/main/default/objects/Maintenance__c/fields/Maintenance_Name__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Name__c</fullName>
    <label>Maintenance Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

internalAMS/force-app/main/default/classes/Maintenance_Status_alert_Batchclass.cls
global class Maintenance_Status_alert_Batchclass implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id,Maintenance_Name__c,Name,Assets__c,Asset_Received_For_Maintenance__c FROM Maintenance__c where Asset_Received_For_Maintenance__c !=True';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Maintenance__c> Maintenance_list) {
       
        List<id> Asset_ids=new list<Id>();
        for(Maintenance__c data:Maintenance_list)
        {
           Asset_ids.add(data.Assets__c) ;
        }
        list<Asset_Assignment__c> Email_list = new list<Asset_Assignment__c>([select id,Asset_Id__c,Employee__c,Employee__r.Email__c from Asset_Assignment__c where Employee__c != null ]);
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        try {
            // Update the Account Record
           // update accList;
        
        } catch(Exception e) {
            System.debug(e);
        }
        
    }   
    
    global void finish(Database.BatchableContext BC) {
        // execute any post-processing operations
  }
}