internalAMS/force-app/main/default/objects/Asset__c/fields/Asset_Status__c.field-meta.xml
<CustomField>
    <fullName>Asset_Status__c</fullName>
    <defaultValue>&quot;Not Assigned&quot;</defaultValue>
    <description>Here, we can know the asset status</description>
    <label>Asset Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Assigned</fullName>
                <default>true</default>
                <label>Not Assigned</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Under Maintenance</fullName>
            </value>
            <value>
                <fullName>Disposed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

internalAMS/force-app/main/default/objects/Asset_Assignment__c/fields/Asset_Id__c.field-meta.xml
<CustomField>
    <fullName>Asset_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset Id</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset__c.Asset_Status__c</field>
            <operation>equals</operation>
            <value>Not Assigned</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Asset Assignments</relationshipLabel>
    <relationshipName>Asset_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

internalAMS/force-app/main/default/objects/Asset_Assignment__c/fields/Is_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Is_Assigned__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>This checkbox shows that this asset is assigned.</inlineHelpText>
    <label>Is Assigned</label>
    <type>Checkbox</type>
</CustomField>

internalAMS/force-app/main/default/classes/Asset_AssignmentTriggerHandler.cls
public class Asset_AssignmentTriggerHandler {
    public static void handleBeforeUpdate(List<Asset_Assignment__c> newAssetAssignments, Map<Id, Asset_Assignment__c> oldAssetAssignmentsMap) {
        // Collect Asset IDs that need to be updated
        Set<Id> assetIdsToUpdate = new Set<Id>();

        for (Asset_Assignment__c newAssignment : newAssetAssignments) {
            Asset_Assignment__c oldAssignment = oldAssetAssignmentsMap.get(newAssignment.Id);

            // Check if isAssigned__c is changing from true to false
            if (oldAssignment.Is_Assigned__c && !newAssignment.Is_Assigned__c) {
                assetIdsToUpdate.add(newAssignment.Asset_Id__c);
            }
        }

        // Query and update Asset records
        List<Asset__c> assetsToUpdate = [
            SELECT Id, Asset_Status__c
            FROM Asset__c
            WHERE Id IN :assetIdsToUpdate
        ];

        for (Asset__c asset : assetsToUpdate) {
            // Update AssetStatus__c to 'Not Assigned' or the appropriate value
            asset.Asset_Status__c = 'Not Assigned';
        }

        // Update Asset records
        update assetsToUpdate;
    }
}