internalAMS/force-app/main/default/objects/Asset__c/fields/Asset_Status__c.field-meta.xml
<CustomField>
    <fullName>Asset_Status__c</fullName>
    <defaultValue>&quot;Not Assigned&quot;</defaultValue>
    <description>Here, we can know the asset status</description>
    <label>Asset Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Assigned</fullName>
                <default>true</default>
                <label>Not Assigned</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Under Maintenance</fullName>
            </value>
            <value>
                <fullName>Disposed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

internalAMS/force-app/main/default/objects/Asset__c/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Godrej</fullName>
            </value>
            <value>
                <fullName>Usha</fullName>
            </value>
            <value>
                <fullName>Durian</fullName>
            </value>
            <value>
                <fullName>Pepperfry</fullName>
            </value>
            <value>
                <fullName>Nikamal</fullName>
            </value>
            <value>
                <fullName>Apple</fullName>
            </value>
            <value>
                <fullName>Asus</fullName>
            </value>
            <value>
                <fullName>Dell</fullName>
            </value>
            <value>
                <fullName>HP</fullName>
            </value>
            <value>
                <fullName>Lenovo</fullName>
            </value>
            <value>
                <fullName>Voltas</fullName>
            </value>
            <value>
                <fullName>Carrier</fullName>
            </value>
            <value>
                <fullName>Hitachi</fullName>
            </value>
            <value>
                <fullName>Lloyd</fullName>
            </value>
            <value>
                <fullName>Panasonic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

internalAMS/force-app/main/default/objects/Asset__c/fields/Equipments__c.field-meta.xml
<CustomField>
    <fullName>Equipments__c</fullName>
    <label>Equipments</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Chair</fullName>
            </value>
            <value>
                <fullName>Table</fullName>
            </value>
            <value>
                <fullName>Cabinet Table</fullName>
            </value>
            <value>
                <fullName>Bookshelves</fullName>
            </value>
            <value>
                <fullName>Cabinets</fullName>
            </value>
            <value>
                <fullName>White Boards</fullName>
            </value>
            <value>
                <fullName>Monitor</fullName>
            </value>
            <value>
                <fullName>Laptop</fullName>
            </value>
            <value>
                <fullName>Printer</fullName>
            </value>
            <value>
                <fullName>Mouse</fullName>
            </value>
            <value>
                <fullName>Keyboard</fullName>
            </value>
            <value>
                <fullName>Fax Machine</fullName>
            </value>
            <value>
                <fullName>Projector</fullName>
            </value>
            <value>
                <fullName>Mobile Phone</fullName>
            </value>
            <value>
                <fullName>Tablet</fullName>
            </value>
            <value>
                <fullName>Data Storage Device</fullName>
            </value>
            <value>
                <fullName>Router</fullName>
            </value>
            <value>
                <fullName>Air conditioning units</fullName>
            </value>
            <value>
                <fullName>Heating systems</fullName>
            </value>
            <value>
                <fullName>Ventilation systems</fullName>
            </value>
            <value>
                <fullName>Thermostats</fullName>
            </value>
            <value>
                <fullName>Ducts</fullName>
            </value>
            <value>
                <fullName>Chillers</fullName>
            </value>
            <value>
                <fullName>Boilers</fullName>
            </value>
            <value>
                <fullName>Fans</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

internalAMS/force-app/main/default/objects/Asset__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Dubai</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

internalAMS/force-app/main/default/objects/Asset__c/fields/Purchased_Amount__c.field-meta.xml
<CustomField>
    <fullName>Purchased_Amount__c</fullName>
    <label>Purchased Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

internalAMS/force-app/main/default/classes/AssetApexController.cls
public class AssetApexController {
            @AuraEnabled(cacheable=true)
            public static List<String> getBrandOptions() {
                List<String> picklistValues = new List<String>();
                Schema.DescribeFieldResult fieldResult = Asset__c.Brand_Name__c.getDescribe();
                List<Schema.PicklistEntry> picklistEntries = fieldResult.getPicklistValues();
                
                for (Schema.PicklistEntry entry : picklistEntries) {
                    picklistValues.add(entry.getLabel());
                }
                
                System.debug('======> Line 36' + picklistValues);
                return picklistValues;
            }
            @AuraEnabled(cacheable=true)
            public static List<String> getEquipmentsOptions() {
                List<String> picklistValues2 = new List<String>();
                Schema.DescribeFieldResult fieldResult = Asset__c.Equipments__c.getDescribe();
                List<Schema.PicklistEntry> picklistEntries = fieldResult.getPicklistValues();
                for (Schema.PicklistEntry entry : picklistEntries) {
                       picklistValues2.add(entry.getLabel());
                    
                }
                System.debug('Line 48'+picklistValues2);
                return picklistValues2;
            }
            @AuraEnabled(cacheable=true)
            public static List<String> getStatusOptions() {
                List<String> picklistValues3 = new List<String>();
                Schema.DescribeFieldResult fieldResult = Asset__c.Asset_Status__c.getDescribe();
                List<Schema.PicklistEntry> picklistEntries = fieldResult.getPicklistValues();
                for (Schema.PicklistEntry entry : picklistEntries) {
                        picklistValues3.add(entry.getLabel());
                    
                }
                System.debug('Line 48'+picklistValues3);
                return picklistValues3; 
            }
            @AuraEnabled(cacheable=true)
            public static List<String> getLocationOptions() {
                List<String> picklistValues4 = new List<String>();
                Schema.DescribeFieldResult fieldResult = Asset__c.Location__c.getDescribe();
                List<Schema.PicklistEntry> picklistEntries = fieldResult.getPicklistValues();
                for (Schema.PicklistEntry entry : picklistEntries) {
                        picklistValues4.add(entry.getLabel());
                    
                }
                System.debug('Line 48'+picklistValues4);
                return picklistValues4; 
              
            }
            @AuraEnabled
            public static string createRecords(string equipmentValuess,string brandnamess,string status,string location,date purchasedate,Integer Amount,integer Number_of_Records) {
                List<Asset__c> newAssets = new List<Asset__c>();
            if(equipmentValuess != null || brandnamess != null || location != null || purchasedate != null || Amount != null){
                for (Integer i = 0; i < Number_of_Records; i++) {
                    Asset__c  new_data= new Asset__c();
                    new_data.Asset_Status__c=status;
                    new_data.Equipments__c=equipmentValuess;
                    new_data.Brand_Name__c=brandnamess;
                    new_data.Location__c=location;
                    new_data.Purchased_Date__c=purchasedate;
                    new_data.Purchased_Amount__c=Amount;
                    newAssets.add(new_data);
                }
            }
            //  if(Number_of_Records==0){
            //     Asset__c  new_data= new Asset__c();
            //     new_data.Asset_Status__c=status;
            //     new_data.Equipments__c=equipmentValuess;
            //     new_data.Brand_Name__c=brandnamess;
            //     new_data.Location__c=location;
            //     Insert new_data;

            //  }
                try {
                    insert newAssets;
                    return 'Success';
                } catch (Exception e) {
                    // Handle exception, log error, or perform other actions
                    throw new AuraHandledException('Error creating records: ' + e.getMessage());
                    
                    
                }
            }
           @AuraEnabled
           public static string createRecordssingle(string equipmentValuess,string brandnamess,string status,string location,date purchasedate,Integer Amount,integer Number_of_Records) 
            {
            if(equipmentValuess != null || brandnamess != null || location != null || purchasedate != null || Amount != null){

                Asset__c  new_data= new Asset__c();
                new_data.Asset_Status__c=status;
                new_data.Equipments__c=equipmentValuess;
                new_data.Brand_Name__c=brandnamess;
                new_data.Location__c=location;
                new_data.Purchased_Date__c=purchasedate;
                new_data.Purchased_Amount__c=Amount;
                
                 try {
                    insert(new_data);
                    return 'success';
                } catch (Exception e) {
                    // Handle the exception
                    System.debug('Exception caught: ' + e.getMessage());
                    return e.getMessage();
                }
            }
            else{
                return 'null data';
            }
               
            }
            
        }