internalAMS/force-app/main/default/objects/Asset__c/fields/Asset_Status__c.field-meta.xml
<CustomField>
    <fullName>Asset_Status__c</fullName>
    <defaultValue>&quot;Not Assigned&quot;</defaultValue>
    <description>Here, we can know the asset status</description>
    <label>Asset Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Assigned</fullName>
                <default>true</default>
                <label>Not Assigned</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Under Maintenance</fullName>
            </value>
            <value>
                <fullName>Disposed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

internalAMS/force-app/main/default/objects/Asset__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Quality Assurance</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

internalAMS/force-app/main/default/objects/Asset__c/fields/Equipments__c.field-meta.xml
<CustomField>
    <fullName>Equipments__c</fullName>
    <label>Equipments</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Chair</fullName>
            </value>
            <value>
                <fullName>Table</fullName>
            </value>
            <value>
                <fullName>Cabinet Table</fullName>
            </value>
            <value>
                <fullName>Bookshelves</fullName>
            </value>
            <value>
                <fullName>Cabinets</fullName>
            </value>
            <value>
                <fullName>White Boards</fullName>
            </value>
            <value>
                <fullName>Monitor</fullName>
            </value>
            <value>
                <fullName>Laptop</fullName>
            </value>
            <value>
                <fullName>Printer</fullName>
            </value>
            <value>
                <fullName>Mouse</fullName>
            </value>
            <value>
                <fullName>Keyboard</fullName>
            </value>
            <value>
                <fullName>Fax Machine</fullName>
            </value>
            <value>
                <fullName>Projector</fullName>
            </value>
            <value>
                <fullName>Mobile Phone</fullName>
            </value>
            <value>
                <fullName>Tablet</fullName>
            </value>
            <value>
                <fullName>Data Storage Device</fullName>
            </value>
            <value>
                <fullName>Router</fullName>
            </value>
            <value>
                <fullName>Air conditioning units</fullName>
            </value>
            <value>
                <fullName>Heating systems</fullName>
            </value>
            <value>
                <fullName>Ventilation systems</fullName>
            </value>
            <value>
                <fullName>Thermostats</fullName>
            </value>
            <value>
                <fullName>Ducts</fullName>
            </value>
            <value>
                <fullName>Chillers</fullName>
            </value>
            <value>
                <fullName>Boilers</fullName>
            </value>
            <value>
                <fullName>Fans</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

internalAMS/force-app/main/default/objects/Asset_Assignment__c/fields/Asset_Id__c.field-meta.xml
<CustomField>
    <fullName>Asset_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset Id</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset__c.Asset_Status__c</field>
            <operation>equals</operation>
            <value>Not Assigned</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Asset Assignments</relationshipLabel>
    <relationshipName>Asset_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

internalAMS/force-app/main/default/objects/Asset_Assignment__c/fields/Assgined_Date__c.field-meta.xml
<CustomField>
    <fullName>Assgined_Date__c</fullName>
    <label>Assgined Date</label>
    <type>Date</type>
</CustomField>

internalAMS/force-app/main/default/objects/Asset_Assignment__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Asset Assignments</relationshipLabel>
    <relationshipName>Asset_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

internalAMS/force-app/main/default/objects/Asset_Assignment__c/fields/Department_Name__c.field-meta.xml
<CustomField>
    <fullName>Department_Name__c</fullName>
    <formula>Employee__r.Department_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Department Name</label>
    <type>Text</type>
</CustomField>

internalAMS/force-app/main/default/objects/Asset_Assignment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Asset Assignments</relationshipLabel>
    <relationshipName>Asset_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

internalAMS/force-app/main/default/objects/Employee__c/fields/Department_Name__c.field-meta.xml
<CustomField>
    <fullName>Department_Name__c</fullName>
    <label>Department Name</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

internalAMS/force-app/main/default/classes/Employee_Handler.cls
public class Employee_Handler {
    public static void Asset_Assigment_to_employee(list<Employee__c> employeedata)
    {
        list<Asset__c> Laptop_Asset_data=new list<Asset__c>([select id,Equipments__c from Asset__c Where Asset_Status__c = 'Not Assigned' and Equipments__c='Laptop']);//getting the laptop data
		list<Asset__c> chair_Asset_data=new list<Asset__c>([select id,Equipments__c from Asset__c Where Asset_Status__c = 'Not Assigned' and Equipments__c='Chair']);//getting the chair data
        list<Asset__c> table_Asset_data=new list<Asset__c>([select id,Equipments__c from Asset__c Where Asset_Status__c = 'Not Assigned' and Equipments__c='Table']);//getting the table data
        list<Asset_Assignment__c> new_Asset_Assignment=new list<Asset_Assignment__c>();
        //assigning assets to the employee
	    for(integer i=0;i<=employeedata.size();i++)
        {
            if(Laptop_Asset_data.size()<=employeedata.size())//checking the availability 
            {
                Asset_Assignment__c laptop=new Asset_Assignment__c();
                laptop.Asset_Id__c=Laptop_Asset_data[i].id;
                laptop.Assgined_Date__c=system.today();
                laptop.Employee__c=employeedata[i].Id;
                laptop.Department__c=employeedata[i].Department_Name__c;
                new_Asset_Assignment.add(laptop);
            }
            if(chair_Asset_data.size()<=employeedata.size()){//checking the availability 
                Asset_Assignment__c chair=new Asset_Assignment__c();
                 chair.Asset_Id__c=Laptop_Asset_data[i].id;
                chair.Assgined_Date__c=system.today();
                chair.Employee__c=employeedata[i].Id;
                chair.Department__c=employeedata[i].Department_Name__c;
                new_Asset_Assignment.add(chair);
            }
             if(table_Asset_data.size()<=employeedata.size()){//checking the availability 
                Asset_Assignment__c table=new Asset_Assignment__c();
                  table.Asset_Id__c=Laptop_Asset_data[i].id;
                table.Assgined_Date__c=system.today();
                table.Employee__c=employeedata[i].Id;
                table.Department__c=employeedata[i].Department_Name__c;
                 new_Asset_Assignment.add(table);
            }
        }
         // Perform the update operation on Asset records
        try {
			insert(new_Asset_Assignment);
            system.debug(new_Asset_Assignment);
        } catch(Exception e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
            
    }
}